SASS-6159: J-3 Create 'UK interest' page - Income from property, pens…
hmrc/income-tax-tailor-returns-frontend pull request #58
Opened 2023-11-15 12:10 UTC by AishaBi

…ions and investments - TYR II

### Description
Please include a brief summary of the change you've made and the issue that it fixes.

### Checklist PR Raiser
### Note: This is just not a tick box, make sure you follow all the below steps
##### Before creating PR
- [ ]  Have you run the tests?
- [ ]  Have you run the it tests?
- [ ]  Have you run the journey tests? (where applicable)
- [ ]  Have you addressed warnings where appropriate?
- [ ]  Have you rebased against the current version of main?
- [ ]  Have you checked code coverage isn’t lower than previously?
- [ ]  Have you done the group review in the team?

##### After PRs been raised
- [ ]  Have you checked the PR Builder passes?

### Checklist PR Reviewer
##### Before Reviewing
- [ ]  Have you pulled the branch down?
- [ ]  Have you assigned yourself to the PR?
- [ ]  Have you moved the task to “in review” on JIRA?
- [ ]  Have you checked to ensure all dependencies are up to date?
- [ ]  Have you checked to ensure its been rebased against the current version of main?

##### Whilst Reviewing
- [ ]  Have you run the tests?
- [ ]  Have you run the it tests?
- [ ]  Have you run the journey tests?
- [ ]  Have you looked at the JIRA story to make sure all Acceptance Criteria has been met?
- [ ]  Have you checked for individual and agent content matching with the prototype? (where applicable)
- [ ]  Have you checked for welsh transaltion for individual and agent? (where applicable)
- [ ]  Have you checked for errors messages for individual and agent on both english and welsh? (where applicable)
- [ ]  Run wave (chrome extension) for accessibility (where applicable)

##### After Reviewing
- [ ]  Have you checked for merge conflicts or any changes in the current main that may affect the current pull request? i.e. does it need another rebase?
- [ ]  Have you checked to make sure there are no builds in the pipeline before you merge?
- [ ]  Have you moved the task to “in pipeline” on Jira?
- [ ]  Demo to Business Analyst

2023-11-16 15:25 UTC, rhysconnor commented
Can we add `override def path: JsPath = JsPath \"propertyPensionsInvestments"\ toString` to Pages.UkInterestPage

2023-11-16 15:47 UTC, rhysconnor requested changes

2023-11-16 15:47 UTC, rhysconnor commented on conf/messages.en
> +ukInterest.error.required = Select if you had income from UK interest, or No, you did not get any income from UK interest
The errors for this has been updated please see comment section of the parent ticket

2023-11-16 15:47 UTC, rhysconnor commented on conf/messages.en
> +###################################  UK interest ###########################################################################################
I know the welsh content isnt ready yet but could we add the english messages into the welsh content just as placeholders?

2023-11-16 15:47 UTC, rhysconnor commented on app/models/propertypensionsinvestments/UkInterest.scala
> +  case object  NoInterest extends WithName("noInterest") with UkInterest
can we align NoInterest

2023-11-20 14:55 UTC, ansahdavid approved these changes

2023-11-20 15:11 UTC, kannanramakrishnan approved these changes

2023-11-20 15:12 UTC, merged